### ISSUE TITLE
Forms Disappeared

### ISSUE THREAD

**Issue by jault3** [getgrav/grav-theme-deliver#11]
I noticed there was a recent update to the grav form plugin https://github.com/getgrav/grav-plugin-form and ever since then, forms disappeared from my site. There was also an update to the deliver theme itself, which I'm not sure is the culprit. 

In any case, this issue can be seen on the demo website at this page http://demo.getgrav.org/deliver-skeleton/contact.

**Comment by flaviocopes** [comment]
I just tried to download the skeleton. It works fine to me. Try the skeleton locally and let me know.

There's an issue probably on the demo deploy. @rhukster pinging you on that.

**Comment by jault3** [comment]
The skeleton also works for me. I checked all versions of plugins that the skeleton had installed that I also had installed and all versions were the same. The frontmatter on the form pages are nearly identical between the skeleton site and my own as well.

I would be interested to see if you find anything in the demo site that caused this as it may also be causing my site to misbehave. Thanks for checking this!

**Comment by flaviocopes** [comment]
The demo didn't have the Form plugin installed, now fixed.

**Comment by jault3** [comment]
Sorry to ask about this again, but I just wanted to confirm. All you did was `bin/gpm install form`?

**Comment by flaviocopes** [comment]
Yes, that was the problem
