### ISSUE TITLE
How to use dropdown menus

### ISSUE THREAD

**Issue by indigo423** [getgrav/grav-theme-deliver#13]
There is a option in the navigation.html.twig which seems to enable dropdown navigation (`theme_config.dropdown.enabled`). I haven't found an example or documentation how to use it?

Help appreciated, thank you in advance.

**Comment by flaviocopes** [comment]
In the Plugin configuration, set https://github.com/getgrav/grav-theme-deliver/blob/develop/deliver.yaml#L3 to true.

You can see that option in the Admin, in the theme configuration.

**Comment by indigo423** [comment]
I've found to enable it, but what is the syntax to add a child entry in the navigation menu?

Thank you for your quick response.

**Comment by flaviocopes** [comment]
The menu will show child pages, so add pages as childs of the top-level page, and they will be added there.

**Comment by indigo423** [comment]
What does it mean "add pages as childs of the top-level page". Is it a subfolder structure or is there an attribute to set?

**Comment by flaviocopes** [comment]
Add pages inside other pages, in a subfolder structure, like in this example: http://learn.getgrav.org/content/content-pages#folders

**Comment by indigo423** [comment]
Thank you this hint helped. I've searched for child pages in the documentation and this was kind of hard to adapt. Thank you for your patience.
