### ISSUE TITLE
Feature request: fixed menu

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-theme-deliver#21]
Hi, I love the Deliver theme!
I have a feature request: is it possible to have a fixed menu (without the logo and social icons) just like Antimatter or Gravi-k. I'm willing to sponsor this feature.

**Comment by flaviocopes** [comment]
Added in 1.6.0 https://github.com/getgrav/grav-theme-deliver/blob/develop/CHANGELOG.md#v160
