### ISSUE TITLE
Portfolio - Scrolls body and not modal.

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav-theme-deliver#3]
When the modal is activated/opened the body continues to scroll with the mouse scroll but the modal stays still. Some screens are unable to see the entire modal and are also unable to scroll to see the rest of the modal.

**Comment by hexplor** [comment]
Thanks. I'm going to check that and eventually release a fix.

**Comment by hexplor** [comment]
Open ***template.css*** from ***css-compiled*** dir and add:
```css
.modal {
  overflow-y: scroll !important;
}
```
Let me know if that fixes the issue.
