### ISSUE TITLE
Blueprints are missing

### ISSUE THREAD

**Issue by jwohlfeil** [getgrav/grav-theme-deliver#31]
I created them, just put them here:
user/themes/deliver/blueprints:
https://www.dropbox.com/s/je2crabjpfy3uj2/theme-blueprints.zip?dl=0

user/blueprints:
https://www.dropbox.com/s/o7zgiimsks5uua1/user-blueprints.zip?dl=0

Hope this helps someone :-)

**Comment by pmoreno-rodriguez** [comment]
The links are no longer available and the issue has no detailed description.
