### ISSUE TITLE
fontawesome usage

### ISSUE THREAD

**Issue by zagwalker** [getgrav/grav-theme-deliver#33]
Hi,

I can see that some sort of fontwesome is being used with the theme. However, it is not standard package since I cant see a lot of fontawesome icons.

Is there a list possible icons to use?

Thanks
Lev

**Comment by atomsmith** [comment]
@zagwalker The theme uses FontAwesome v4.5, which was released in November 2015. Upgrading it to FontAwesome v5.xx would be a fair amount of work, in my non-expert opinion. However, I have an open pull request #28 that at least gets the theme to v4.7. I needed this to obtain a Meetup.com icon on my website.

**Comment by zagwalker** [comment]
Thanks @atomsmith, its enough for me at this stage. Just wanted to know what icons I can use.
