### ISSUE TITLE
The reserved indicator "@" cannot start a plain scalar

### ISSUE THREAD

**Issue by Machion** [getgrav/grav-theme-deliver#37]
Using grav 1.7.0 and deliver 1.7.1
the Grav Yaml Linter found an error at _/user/themes/deliver/blueprints/blog.yaml_ saying: 

The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 2 (near "@extends:")

**Comment by mahagr** [comment]
As a workaround you can set `Configuration > System > Advanced > YAML Compatibility` to on.

**Comment by Machion** [comment]
Thanks for the tip, but it doesn't seem to work. At least the bug doesn't affect site functionality (for now). 
Interestingly grav-backend is much faster with YAML compatibility on.
