### ISSUE TITLE
Theme is incompatibility with Grav 1.7

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-theme-deliver#39]
Template *user/themes/deliver/templates/partials/simplesearch_base.html.twig* contains the following code which lead to incompatibility with Grav 1.7:
line 27:    `{{ assets.css() }}`
line 36:    `{{ assets.js() }}`

**Comment by mahagr** [comment]
@rhukster Needs a release!

**Comment by pmoreno-rodriguez** [comment]
Fixed by @mahagr in [commit 9ab1569](https://github.com/getgrav/grav-theme-deliver/commit/9ab156987945e413b5c62b1a10fd7a1a01c2556a) and ready in version 1.7.2
