### ISSUE TITLE
What grid system? 3rd party Documentation?  Best-practices?  

### ISSUE THREAD

**Issue by mediadoneright** [getgrav/grav-theme-deliver#4]
Great theme!  I really like how everything is broken into components ... but since I'm new to both grav and Deliver, I'm not sure where to find things or bast practices for this theme?  I should mention I've already read [about theming on grav](http://learn.getgrav.org/themes).

I'm curious about the naming conventions in the theme.  _(`modular` AND `modules`?  multiple `nucleus` AND `template` folders.  also many duplicate file names (`_base.scss`, `_core.scss`). **wtf?!** :smiling_imp: very confusing at first glance)._  It seems this is built using constructs of __grav antimatter__?  (If so, can I suggest a mention in [README.md](README.md)).  

_Ugh!  In the process of putting together this issue I've discovered [Deliver was grav's default theme](/getgrav/grav-theme-deliver/blob/208595fc6e8bdd1e43a361354314be5f42ed8dca/README.md). Still begs the question..._   

## Grid system?
Is there a 3rd party grid framework this is built-upon?  I'd like more documentation to read on best practices on how to modify or apply layouts.  ~~Can you point me in a useful direction besides [grav themes](http://learn.getgrav.org/themes)?~~

**Comment by hexplor** [comment]
Hello mediadoneright,
Deliver is obviously not a default grav theme :) It's a mistake in readme file. Thanks for pointing that out. 
Theme is built using our internal framework. It's work in progress so there's no documentation yet. In scss directory you have template.scss which is split into other scss files, basically website parts. You can start from here to see how it's built. Of course not all bits are used and you're gonna need scss compiler.

**Comment by mediadoneright** [comment]
@hexplor thanks for the info.  I should have figured out you borrowed from antimatter as a start.

The framework seems nice, but I was hoping it was built on 3rd party system that _already had some existing documentation_ Good luck with that.  :wink: 

Think I might move on to another more documented theme for now, maybe something based on bootstrap, etc.
