### ISSUE TITLE
Issues in pages blueprints

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-theme-deliver#5]
A couple issues related to this theme only:

See https://github.com/getgrav/grav-plugin-admin/issues/212

Issue in Modular pages:

> The Media page just has Files title and clicking Add Item just inserts another blank box. It does not seem functional in the Normal Edit view.

Issue for blog item page types: (maybe it should use the taxonomy type like Antimatter?)

> I also am finding on editing Blog items in Normal mode, that when I update author or tags, they do not change. Only when I go into Expert mode can I save those changes.

**Comment by hexplor** [comment]
That was leftover after Deliver conversion from Antimatter. Changes are in in "develop" branch. Can anybody test if everything is fine before i release ?

**Comment by flaviocopes** [comment]
Works fine for me! :+1:

**Comment by redlabmedia** [comment]
Updating the author in Normal mode works now. However, I select one tag in Normal mode and it adds all tags. Also, the Media->Files function still does not work.

**Comment by hexplor** [comment]
@redlabmedia adding Media -> Files shouldn't be even possible. I removed that because it was an leftover from old antimatter theme. Make sure you update  theme properly. Inside blueprints "dir" there should be only one file.
