### ISSUE TITLE
Responsive: column headers not displayed when table switches to paragraphs

### ISSUE THREAD

**Issue by reachcontent** [getgrav/grav-theme-deliver#6]
With reference to the style defined for the Deliver skeleton, About page:
the table set up in the _intro_ part disapears when you reduce the screen width below ~670px.
The 3-column table switches to a series of 3 paragraphs but the former column headers are lost.

**Comment by hexplor** [comment]
Looking :)

**Comment by hexplor** [comment]
Can you make a screenshot of what do you mean exactly ? I checked theme on various screen sizes and everything seems to be fine. Only thing missing are paragraphs titles which was intentional (although i'm considering bringing this back).

**Comment by reachcontent** [comment]
Ok, I was speaking of the paragraph titles disappearing, I didn't know if it was intentional or not.
Thank you)

**Comment by hexplor** [comment]
BTW. If you want to change that behavior, just open *scss/template/modular/_bottom.scss* and on line 48 remove:
```scss
@include breakpoint(mobile-only) {
                    display: none;
                }
```
