### ISSUE TITLE
Slideshow arrows not resizing well

### ISSUE THREAD

**Issue by ArnauBlanch** [getgrav/grav-theme-deliver#8]
Hi,
I noticed that the buttons to change the slide on the homepage don't resize as they should in a tablet (**iPad**).

![iPad screenshot](https://cloud.githubusercontent.com/assets/5014931/12245240/c6a2a1c6-b8a7-11e5-8a05-bf2931533a51.png)

I hope someone can fix it. I've attached you a screenshot.

Thanks and good work!

**Comment by hexplor** [comment]
Hi,
Works fine for me. Tested on my local install and on demo website. Does that issue occurs on your local install or on our demo ?

**Comment by ArnauBlanch** [comment]
On both sites. :(

El dt., 12 gen., 2016 11:16 Karol Orzeł <notifications@github.com> va
escriure:

**Comment by DimitriSteyaert** [comment]
![2016-01-20 20 41 00](https://cloud.githubusercontent.com/assets/3986313/12460884/523e6bce-bfb6-11e5-826d-1139ee128413.png)
I have the same thing in Chrome on my iPhone for both the demo site and my own website (see screenshot)

**Comment by hexplor** [comment]
Commited fix to theme - develop branch. Please check if it works :)

**Comment by DimitriSteyaert** [comment]
Ok, tested and working. Perfect! :+1:
